# Generated by Django 4.2.5 on 2023-09-29 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=300, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meal_category', models.CharField(choices=[('starters', 'Starters'), ('salads', 'Salads'), ('soup', 'Soup'), ('entrees', 'Entrees'), ('dessert', 'Dessert'), ('beverages', 'Beverages')], max_length=30)),
                ('status', models.IntegerField(choices=[(0, 'Not Avail'), (1, 'Available')], default=1)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
